import Image from "next/image";
import { Col, Container, PrimaryInput, Row } from "../components";
import { useTrans } from "../hooks";
import { MainLayout } from "../layouts";
import styles from "../styles/modules/home.module.scss";

const Home = ({ locale, locales }) => {
  const { trans, changeLocale } = useTrans(locale, locales);

  return (
    <MainLayout
      title="Create Next App"
      description="Generated by create next app"
    >
      <Container>
        <Row>
          <Col xl={4} lg={6} md={12}>
            <p className={styles.para}>Paragraph</p>
          </Col>
          <Col xl={4} lg={6} md={12}>
            <p className={styles.para}>Paragraph</p>
          </Col>
          <Col xl={4} lg={6} md={12}>
            <p className={styles.para}>Paragraph</p>
          </Col>
        </Row>
      </Container>
    </MainLayout>
  );
};

export default Home;

export async function getServerSideProps(context) {
  return {
    props: {
      locales: context.locales,
      locale: context.locale,
    }, // will be passed to the page component as props
  };
}
